apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: gitops-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://gitlab.com/your-org/gitops-repo.git
  branch: main
  secretRef:
    name: flux-git-auth

